spring:
  application:
    name: BookStoreWebApp
  datasource:
    username: root
    password: ${MYSQL_ROOT_PASSWORD}
    url: jdbc:mysql://localhost:3306/book_store?useSSL=false&allowPublicKeyRetrieval=true